
[erddaputil]
secret_key = "foo"

[erddaputil.erddap]
big_parent_directory = "C:/my/storage"

[logging]
version = 1

[logging.root]
level = "INFO"
handlers = ["console"]

[logging.handlers.console]
class = "logging.StreamHandler"
formatter = "brief"
level = "INFO"
stream = "ext://sys.stdout"

[logging.formatters.brief]
format = "%(asctime)s [%(levelname)s] %(message)s"