services:
  metrics:
    build: .
    command: ["webserver"]
    volumes:
      - ".erddaputil.example.toml:/erddaputil/config/.erddaputil.toml"
    ports:
      - "8080:9172"
  erddaputil:
    build: .
    volumes:
      - "./test_config:/erddap-example"
      - "download_data:/cluster_data"
      - ".erddaputil.example.toml:/erddaputil/config/.erddaputil.toml"
      - ".clusterman.example.toml:/erddaputil/config/.clusterman.toml"
    depends_on:
      - metrics
volumes:
  download_data: