   services:

     # ERDDAP
     erddap:
       image: axiom/docker-erddap:2.23-jdk17-openjdk
       volumes:
         - "ephemeral-data:/erddap_data"
         - "persistent-data:/persistent_data"
         - "erddap-content:/usr/local/tomcat/content/erddap"
       ports:
         - "8080:8080"
       environment:
         - "ERDDAP_bigParentDirectory=/erddap_data"
       networks:
         - erddap-network

     # Management Daemon
     erddaputil_daemon:
       image: dfomeds/erddaputil:v0.1.0
       volumes:
         - "ephemeral-data:/erddap_data"
         - "persistent-data:/persistent_data"
         - "erddap-content:/erddap_content"
         - "./erddaputil_config:/erddap_util/config"
       networks:
         - erddap-network

     # Web Application
     erddaputil_webapp:
       image: dfomeds/erddaputil:v0.1.0
       command: ["webserver"]
       volumes:
         - "ephemeral-data:/erddap_data"
         - "persistent-data:/persistent_data"
         - "erddap-content:/erddap_content"
         - "./erddaputil_config:/erddap_util/config"
       ports:
         - "9173:9173"
       networks:
         - erddap-network

     # AMPQ Listener
     erddaputil_ampq:
       image: dfomeds/erddaputil:v0.1.0
       command: ["ampq"]
       volumes:
         - "ephemeral-data:/erddap_data"
         - "persistent-data:/persistent_data"
         - "erddap-content:/erddap_content"
         - "./erddaputil_config:/erddap_util/config"
       networks:
         - erddap-network

   networks:
     erddap-network:

   volumes:
     ephemeral-data:
     persistent-data:
     erddap-content: